packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild

overrides:
  "puppeteer-core": 25.10.0
  "@puppeteer/browsers": 3.2.2
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  '@joohw/boss-cli@0.6.6': patches/@joohw__boss-cli@0.6.6.patch
