import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
const web = new URL('../../web/', import.meta.url).pathname;
const requireWeb = createRequire(path.join(web, 'package.json'));
const { createServer } = await import(requireWeb.resolve('vite'));
const { default: react } = await import(requireWeb.resolve('@vitejs/plugin-react'));
const { default: tailwind } = await import(requireWeb.resolve('@tailwindcss/postcss'));
const dir = await mkdtemp(path.join(web, '.major-catalog-fixture-'));
const output = new URL('../../../artifacts/major-catalog-20260908/', import.meta.url).pathname;
await mkdir(output, {recursive:true});
const groups = [{label:'语言类',options:['英语','法语','日语','德语','俄语','韩语']},{label:'经管类',options:['电子商务类','工商管理类']},{label:'文史哲类',options:['新闻传播类']}];
const snapshot = { positionId:'position', bossJobId:'job',bossJobName:'亚马逊运营',fetchedAt:new Date().toISOString(),majorGroups:groups,majorAliases:{新闻传播学类:'新闻传播类'},fields:{major:[...groups.flatMap(g=>g.options),'新闻传播学类'],keyword1:['英语读写','店铺运营']} };
await writeFile(path.join(dir,'index.html'),'<html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="./fixture.tsx"></script></html>');
await writeFile(path.join(dir,'fixture.tsx'),`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{BossDynamicFilters}from'../app/boss-dynamic-filters';import'../app/globals.css';function Fixture(){const[value,onChange]=useState({mode:'custom',fields:{major:['新闻传播学类']}});const[snapshot,onOptionsChange]=useState(null);return <main className="mx-auto max-w-3xl p-4"><BossDynamicFilters positionId="position" bossJobId="job" controlApi={location.origin} {...{value,onChange,snapshot,onOptionsChange}}/><output id="value">{JSON.stringify(value)}</output></main>};createRoot(document.getElementById('root')).render(<Fixture/>);`);
const server = await createServer({configFile:false,root:web,plugins:[react()],resolve:{alias:{'@':web}},define:{'process.env.NEXT_PUBLIC_CONTROL_API_URL':'""'},css:{postcss:{plugins:[tailwind()]}},server:{port:3038,strictPort:true,host:'127.0.0.1'},logLevel:'warn'});
await server.listen();
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage();const errors=[];let fail=false;let wrongJob=false;
page.on('pageerror',error=>errors.push(error.message));
await page.setRequestInterception(true);
page.on('request',request=>{const url=new URL(request.url());if(!['localhost','127.0.0.1'].includes(url.hostname))return request.abort();if(url.pathname.startsWith('/api/'))return request.respond({status:fail?503:200,contentType:'application/json',body:JSON.stringify(fail?{message:'测试：BOSS 暂时繁忙'}:{...snapshot,bossJobId:wrongJob?'another':snapshot.bossJobId})});return request.continue()});
const click=async label=>{const h=await page.waitForFunction(label=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()===label&&!b.disabled),{},label);await h.asElement().click();await h.dispose()};
const waitText=text=>page.waitForFunction(text=>document.body.innerText.includes(text),{},text);
const selected=()=>page.$eval('#value',el=>JSON.parse(el.textContent).fields.major);
try{
  await page.setViewport({width:1280,height:1000});await page.goto(`http://127.0.0.1:3038/${path.basename(dir)}/index.html`,{waitUntil:'networkidle0'});
  await click('一键获取 BOSS VIP 筛选');await waitText('已更新');
  assert.deepEqual(await selected(),['新闻传播学类']);
  assert.equal(await page.$$eval('[aria-label="专业选项"] button',nodes=>nodes.filter(n=>n.textContent.includes('新闻传播')).length),1);
  await page.select('select','经管类');await page.type('input[type="search"]','英语');await waitText('已搜索全部分类');
  assert.equal(await page.$$eval('[aria-label="专业选项"] button',nodes=>nodes.length),1);await click('英语');
  assert.deepEqual(await selected(),['新闻传播学类','英语']);
  await click('一键获取 BOSS VIP 筛选');await page.waitForFunction(()=>!document.querySelector('section').getAttribute('aria-busy')||document.querySelector('section').getAttribute('aria-busy')==='false');
  assert.deepEqual(await selected(),['新闻传播学类','英语']);
  await page.screenshot({path:path.join(output,'english-search-desktop.png')});
  await page.$eval('input[type="search"]',el=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'');el.dispatchEvent(new Event('input',{bubbles:true}))});
  await page.select('select','语言类');await click('法语');await click('日语');await click('德语');
  assert.equal((await selected()).length,5);
  assert.equal(await page.$$eval('[aria-label="专业选项"] button',nodes=>nodes.filter(n=>n.disabled).length),2);
  await page.click('[aria-label="移除专业 新闻传播学类"]');await click('俄语');
  await page.setViewport({width:375,height:1000});await page.screenshot({path:path.join(output,'english-major-mobile.png')});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.type('input[type="search"]','不存在的专业');await waitText('未找到匹配专业');
  fail=true;await click('一键获取 BOSS VIP 筛选');await waitText('测试：BOSS 暂时繁忙');assert.equal((await selected()).length,5);
  fail=false;wrongJob=true;await click('一键获取 BOSS VIP 筛选');await waitText('岗位已变化');assert.equal((await selected()).length,5);
  assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,englishSearchAcrossCategories:true,oldRuleAliasPreserved:true,refreshPreservesSelections:true,limitFive:true,mobile375:true,noResults:true,requestFailure:true,wrongJobRejected:true}));
}finally{await browser.close();await server.close();await rm(dir,{recursive:true,force:true})}
