'use client';
import { Button } from '@/components/ui/button'; import { inputClass } from '../workspace-ui';
export type TreeNode={id:string;kind:'group'|'leaf';operator?:'AND'|'OR'|'NOT';leafType?:'tem8'|'education'|'experience'|'keyword'|'boss_tags';value?:string;children?:TreeNode[]};
const id=()=>crypto.randomUUID(); export const initialTree=():TreeNode=>({id:id(),kind:'group',operator:'AND',children:[{id:id(),kind:'leaf',leafType:'tem8',value:'0.8'}]});
export function serializeTree(n:TreeNode):unknown{if(n.kind==='group')return{operator:n.operator,children:(n.children??[]).map(serializeTree)};if(n.leafType==='tem8')return{type:'tem8',minimumConfidence:Number(n.value||.8),unknownPolicy:'manual_review'};if(n.leafType==='education')return{type:'education_level',minimum:n.value||'bachelor',unknownPolicy:'manual_review'};if(n.leafType==='experience')return{type:'range',field:'yearsOfExperience',minimum:Number(n.value||0),unknownPolicy:'manual_review'};if(n.leafType==='boss_tags')return{type:'enum',field:'bossPlatformTags',values:(n.value||'985').split(',').map(x=>x.trim()).filter(Boolean),mode:'any',match:'contains',unknownPolicy:'manual_review'};return{type:'keyword',field:'all',values:(n.value||'').split(',').map(x=>x.trim()).filter(Boolean),mode:'all',unknownPolicy:'manual_review'}}
function update(root:TreeNode,target:string,fn:(n:TreeNode)=>TreeNode):TreeNode{if(root.id===target)return fn(root);return root.kind==='group'?{...root,children:(root.children??[]).map(x=>update(x,target,fn))}:root}
function remove(root:TreeNode,target:string):TreeNode{return root.kind==='group'?{...root,children:(root.children??[]).filter(x=>x.id!==target).map(x=>remove(x,target))}:root}
function Node({node,root,onChange}:{node:TreeNode;root:boolean;onChange:(fn:(n:TreeNode)=>TreeNode)=>void}){return <div className="space-y-2 rounded-lg border bg-white p-3">{node.kind==='group'?<><div className="flex flex-wrap gap-2"><select className={inputClass} value={node.operator} onChange={e=>onChange(r=>update(r,node.id,n=>({...n,operator:e.target.value as TreeNode['operator'],children:e.target.value==='NOT'?(n.children??[]).slice(0,1):n.children})))}><option>AND</option><option>OR</option><option>NOT</option></select><Button type="button" variant="outline" onClick={()=>onChange(r=>update(r,node.id,n=>({...n,children:[...(n.children??[]),{id:id(),kind:'leaf',leafType:'keyword',value:'TypeScript'}]})))}>+ 条件</Button><Button type="button" variant="outline" disabled={node.operator==='NOT'||(node.children??[]).length>8} onClick={()=>onChange(r=>update(r,node.id,n=>({...n,children:[...(n.children??[]),{id:id(),kind:'group',operator:'AND',children:[{id:id(),kind:'leaf',leafType:'keyword',value:'关键词'}]}]})))}>+ 条件组</Button>{!root?<Button type="button" variant="destructive" onClick={()=>onChange(r=>remove(r,node.id))}>删除组</Button>:null}</div><div className="space-y-2 border-l-2 border-primary/30 pl-3">{(node.children??[]).map(c=><Node key={c.id} node={c} root={false} onChange={onChange}/>)}</div></>:<div className="grid gap-2 md:grid-cols-[180px_1fr_auto]"><select className={inputClass} value={node.leafType} onChange={e=>onChange(r=>update(r,node.id,n=>({...n,leafType:e.target.value as TreeNode['leafType'],value:''})))}><option value="tem8">TEM8 专八</option><option value="education">最低学历</option><option value="experience">最低经验</option><option value="boss_tags">BOSS 院校标签</option><option value="keyword">关键词</option></select>{node.leafType==='education'?<select className={inputClass} value={node.value} onChange={e=>onChange(r=>update(r,node.id,n=>({...n,value:e.target.value})))}><option value="associate">专科</option><option value="bachelor">本科</option><option value="master">硕士</option><option value="doctor">博士</option></select>:<input className={inputClass} value={node.value??''} placeholder={node.leafType==='tem8'?'置信度 0-1':node.leafType==='experience'?'年数':'多个值用逗号分隔'} onChange={e=>onChange(r=>update(r,node.id,n=>({...n,value:e.target.value})))}/>}<Button type="button" variant="destructive" onClick={()=>onChange(r=>remove(r,node.id))}>删除</Button></div>}</div>}
export function RuleTreeBuilder({value,onChange}:{value:TreeNode;onChange:(v:TreeNode)=>void}){return <Node node={value} root onChange={fn=>onChange(fn(value))}/>}
