ALTER TABLE integration_outbox_events
  ADD COLUMN IF NOT EXISTS sequence_no bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS integration_outbox_sequence_uidx
  ON integration_outbox_events (sequence_no);

CREATE INDEX IF NOT EXISTS integration_outbox_correlation_sequence_idx
  ON integration_outbox_events (correlation_id, sequence_no, status);
