'use client';
import { useCallback,useEffect,useState } from 'react';
import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge';
import { AuthGate } from '../auth-gate'; import { WorkspaceShell } from '../workspace-shell';
import { Empty,inputClass,Notice,Panel } from '../workspace-ui';
import { apiJson,formatDate,postJson,Row,rows,stringValue } from '../workspace-utils'; import { CandidateTools } from './candidate-tools';
function Content(){
 const [pipe,setPipe]=useState<Row>({items:[],total:0}),[dept,setDept]=useState<Row>({}),[collab,setCollab]=useState<Row>({}),[pick,setPick]=useState<Row|null>(null),[filter,setFilter]=useState('all'),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const q=filter==='all'?'':'&stage='+filter;const [p,d]=await Promise.all([apiJson<Row>('/api/pipeline?limit=50'+q),apiJson<Row>('/api/department/workspace')]);setPipe(p);setDept(d)}catch(e){setError(e instanceof Error?e.message:String(e))}},[filter]);
 const detail=useCallback(async(id?:string)=>setCollab(await apiJson<Row>('/api/collaboration'+(id?'?stateId='+id:''))),[]); useEffect(()=>{const timer=window.setTimeout(()=>{void load();void detail()},0);return()=>window.clearTimeout(timer)},[load,detail]);
 async function act(job:()=>Promise<unknown>,ok:string){try{await job();setMessage(ok);setError(null);await load();await detail(pick?stringValue(pick.stateId):undefined)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const items=rows(pipe.items),stages=rows(dept.stages),users=rows(dept.users),work=rows(collab.workItems),interviews=rows(collab.interviews),timeline=[...rows(collab.activities),...rows(collab.notes)],stateId=pick?stringValue(pick.stateId):'';
 return <WorkspaceShell current="/pipeline" title="招聘流程与协作" description="分岗位阶段、时间线、备注、待办、面试和反馈均可追溯。"><Notice error={error} message={message}/><div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]">
  <Panel title="候选人管道" description={`共 ${String(typeof pipe.total==='number'?pipe.total:0)} 条申请（服务端分页）`}><select className={inputClass} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部阶段</option>{stages.map(s=><option key={stringValue(s.key)} value={stringValue(s.key)}>{stringValue(s.label)}</option>)}</select>{items.length?items.map(i=><button key={stringValue(i.stateId)} className={`w-full rounded-lg border p-3 text-left ${pick?.stateId===i.stateId?'border-primary bg-primary/5':''}`} onClick={()=>{setPick(i);void detail(stringValue(i.stateId))}}><b>{stringValue(i.name)}</b> <Badge variant="outline">{stringValue(i.positionName)}</Badge> <Badge>{stringValue(i.stage)}</Badge>{i.doNotContact?<Badge variant="destructive">禁止联系</Badge>:null}<p className="mt-1 text-xs text-muted-foreground">规则 {stringValue(i.ruleDecision)} · 审核 {stringValue(i.reviewStatus)}</p></button>):<Empty/>}</Panel>
  <Panel title={pick?stringValue(pick.name):'候选人操作'}>{!pick?<Empty>先选择候选人</Empty>:<><div className="flex flex-wrap gap-2">{stages.map(s=><Button size="sm" variant={pick.stage===s.key?'default':'outline'} key={stringValue(s.key)} onClick={()=>void act(()=>postJson(`/api/pipeline/${stateId}/stage`,{stage:s.key,rejectionReason:s.key==='rejected'?'不符合当前岗位要求':null}),'阶段已更新')}>{stringValue(s.label)}</Button>)}</div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>postJson(`/api/pipeline/${stateId}/notes`,{body:f.get('body'),mentionedUserIds:[]}),'备注已添加')}}><input className={inputClass} name="body" placeholder="备注 / @协作者" required/><Button>添加</Button></form><Button variant="destructive" onClick={()=>void act(()=>postJson('/api/talent/do-not-contact',{candidateId:pick.candidateId,active:!pick.doNotContact,reason:'HR 人工控制'}),'禁止联系状态已更新')}>{pick.doNotContact?'解除禁止联系':'设为禁止联系'}</Button><form className="grid gap-2 rounded-lg bg-muted/40 p-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>postJson('/api/collaboration/work-items',{stateId,assignedTo:f.get('user'),title:f.get('title'),dueAt:f.get('due')||null}),'待办已创建')}}><input className={inputClass} name="title" placeholder="跟进事项" required/><select className={inputClass} name="user" required><option value="">负责人</option>{users.map(u=><option key={stringValue(u.id)} value={stringValue(u.id)}>{stringValue(u.displayName)}</option>)}</select><input className={inputClass} name="due" type="datetime-local"/><Button>创建跟进</Button></form><CandidateTools stateId={stateId} users={users} interviews={interviews} act={act}/></>}</Panel>
 </div><div className="grid gap-5 md:grid-cols-2"><Panel title="跟进待办">{work.length?work.map(w=><div key={stringValue(w.id)} className="rounded-lg border p-3 text-sm"><b>{stringValue(w.title)}</b><p>{stringValue(w.assignedTo)} · {formatDate(w.dueAt)}</p>{w.status==='open'?<Button size="sm" onClick={()=>void act(()=>postJson(`/api/collaboration/work-items/${stringValue(w.id)}/complete`,{}),'待办已完成')}>完成</Button>:null}</div>):<Empty/>}</Panel><Panel title="候选人时间线">{timeline.length?timeline.map((a,n)=><div key={stringValue(a.id)||n} className="border-l-2 pl-3 text-sm"><p>{stringValue(a.summary)||stringValue(a.body)}</p><small>{formatDate(a.createdAt)}</small></div>):<Empty/>}</Panel></div></WorkspaceShell>
}
export function PipelineClient(){return <AuthGate><Content/></AuthGate>}
